export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as QuickStart } from './QuickStart';
export { default as Features } from './Features';
export { default as Reviews } from './Reviews';
export { default as GetStarted } from './GetStarted';
export { default as Solutions } from './Solutions';
export { default as Browsers } from './Browsers';
export { default as Places } from './Places';
